[package]
name = "wot"
version = "0.1.0"
edition = "2021"
description = "Web of Things (WoT)"
license = "MIT"
repository = "https://github.com/sifis-home/wot"
keywords = ["wot", "WebofThings"]

[dependencies]
wot-td = "0.1"
wot-serve = "0.1"
wot-discovery = "0.1"
